In [1]:
import numpy as np

**Instructions to Follow (Failing to follow these will result mark deductions).**


1.   You can not use any built-in function except len()
2.   You can not use any other python collections except array (e.g: tuptle, dictionaries etc.).
3. We will initialize a new array using numpy library. We have to mention the fixed size during initialization. There might be two approach.

  i. arr = np.array([None] * 10) #Initializing an array length 10 with values None.

  ii. arr = np.array([10, 20, 30, 40]) #Initializing an array length 4 with the values.
4. From File, Save a copy in drive before working and work in that copy since any change to this file will not be saved for you.






In [2]:
# You must run this cell to install dependency
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np

/usr/local/lib/python3.10/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


You will see the status Accepted after completion if your code is correct.

If your function is wrong you will see wrong[correction percentage]

Do not change the driver code statements. You can only change the input values to test your code.

In [ ]:
# Test 01: Play Right
def playRight(sequence, beats):
    # TO DO
    i = 0
    while i < len(beats):
      if beats[i] == 1:
        num = len(sequence) - 1
        while num > 0:
          temp = sequence[num]
          sequence[num] = sequence[num-1]
          sequence[num-1] = temp
          num -= 1
      i += 1
    return sequence

print("///  Test 01: Play Right  ///")
sequence = np.array([10, 20, 30, 40, 50, 60])
beats = np.array([1, 0, 0, 1, 0, 1])
returned_value = playRight(sequence, beats)
print(f'Task 1: {returned_value}')  # This should print [40, 50, 60, 10, 20, 30]

///  Test 01: Play Right  ///
Task 1: [40 50 60 10 20 30]


In [3]:
# Test 02: Discard Cards
def discardCards(cards,number):
  # TO DO
  i = 0
  while (i < len(cards)):
    if cards[i] == number:
      cards[i] = 0
      num = len(cards) - 1
      j = i
      while j < num:
        cards[j] = cards[j+1]
        cards[j+1] = 0
        j += 1
    else:
      i += 1
  return cards


print("///  Test 02: Discard Cards  ///")
cards = np.array([1,2,3,2,8,2,2,5,7])
returned_value = discardCards(cards, 2)
print(f'Task 2: {returned_value}') # This should print [1, 3, 8, 5, 7, 0, 0, 0, 0]
unittest.output_test(returned_value, np.array([1, 3, 8, 5, 7, 0, 0, 0, 0]))

///  Test 02: Discard Cards  ///
Task 2: [1 3 8 5 7 0 0 0 0]
Accepted


In [ ]:
#Test 03: Merge Lineup
def mergeLineup(pokemon_1, pokemon_2):
  result = np.array([0]*len(pokemon_1)) #this array stores the resulting array
  # TO DO
  i = 0
  j = len(pokemon_2) - 1
  while i <= len(pokemon_1)-1:
    if pokemon_2[j] == None:
      temp = pokemon_1[i] + 0
      result[i] = temp
    elif pokemon_1[i] == None:
      temp = 0 + pokemon_2[j]
      result[i] = temp
    else:
      temp = pokemon_1[i] + pokemon_2[j]
      result[i] = temp
    i += 1
    j -= 1
  return result





print("///  Test 03: Merge Lineup  ///")
pokemon_1 = np.array([12, 3, 25, 1, None])
pokemon_2 = np.array([5, -9, 3, None, None] )
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 3: {returned_value}') # This should print [12, 3, 28, -8, 5]
unittest.output_test(returned_value, np.array([12, 3, 28, -8, 5]))

pokemon_1 = np.array([4, 5, -1, None, None])
pokemon_2 = np.array([2, 27, 7, 12, None])
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 3: {returned_value}') # This should print [4,17,6,27,2]
unittest.output_test(returned_value, np.array([4,17,6,27,2]))

///  Test 03: Merge Lineup  ///
Task 3: [12  3 28 -8  5]
Accepted
Task 3: [ 4 17  6 27  2]
Accepted


In [ ]:
# Test 04: Balance your Salami
def balanceSalami(salami):
  # TO DO
  sum = 0
  for i in range(len(salami)):
    sum += salami[i]
  i = 0
  new = 0
  res = False
  while i < len(salami):
    sum = sum - salami[i]
    new = new + salami[i]
    if sum == new:
      res = True
    i += 1
  return res

print("///  Test 04: Balance Your Salami  ///")
salami = np.array([1, 1, 1, 2, 1])
returned_value = balanceSalami(salami)
print(f'Task 4: {returned_value}') # This should print True
unittest.output_test(returned_value, True)

salami = [2, 1, 1, 2, 1]
returned_value = np.array(balanceSalami(salami))
print(f'Task 4: {returned_value}') # This should print False
unittest.output_test(returned_value, False)

salami = [10, 3, 1, 2, 10]
returned_value =  np.array(balanceSalami(salami))
print(f'Task 4: {returned_value}') # This should print True
unittest.output_test(returned_value, True)

///  Test 04: Balance Your Salami  ///
Task 4: True
Accepted
Task 4: False
Accepted
Task 4: True
Accepted


In [5]:
# Test 05: Protecc Salami
def protectSalami(salami):
  # TO DO
  unique_notes = np.array([0]*len(salami))
  frequency = np.array([0]*len(salami))
  flag = False
  i = 0
  while i < len(salami):
    if salami[i] not in unique_notes:
      unique_notes[i] = salami[i]
    i += 1
  print(unique_notes)

  for j in range(len(salami)):
    if salami[j] in unique_notes:
      frequency[salami[j]] += 1
  print(frequency)

  for k in range(len(frequency)-1):
     if frequency[k]>=2:
      for l in range(k+1,len(frequency)):
        if frequency[k]==frequency[l]:
          flag=True
          return flag
  return flag

print("///  Test 05: Protecc Salami  ///")
salami = np.array([4,5,6,6,4,3,6,4])
returned_value = protectSalami(salami)
print(f'Task 5: {returned_value}') # This should print True
unittest.output_test(returned_value, True)

salami = np.array([3,4,6,3,4,7,4,6,8,6,6])
returned_value = protectSalami(salami)
print(f'Task 5: {returned_value}') # This should print False
unittest.output_test(returned_value, False)

///  Test 05: Protecc Salami  ///
[4 5 6 0 0 3 0 0]
[0 0 0 1 3 1 3 0]
Task 5: True
Accepted
[3 4 6 0 0 7 0 0 8 0 0]
[0 0 0 2 3 0 4 1 1 0 0]
Task 5: False
Accepted


BONUS TASK (Ungraded)

In [ ]:
# Test 06: Odd Even Wave
def waveYourFlag(arr):
  # TO DO
  new_arr = np.array([0]*len(arr))
  i = 0
  while i < len(arr)-1:
    if ((arr[i])%2) == 0 and ((arr[i+1])%2) == 0:
      new_arr[i] = arr[i]
    else:
      temp = arr[i]
      new_arr[i] = arr[i+1]
      new_arr[i+1] = temp

    i += 1

  return new_arr

print("///  Test 06: Odd Even Wave  ///")
arr = np.array([2,12,3,8,1,5])
returned_value = waveYourFlag(arr)
print(f'Task 6: {returned_value}') # This should print [2,3,12,1,8,5]
unittest.output_test(returned_value, np.array([2,3,12,1,8,5]))

arr = np.array([45,23,78,84,41])
returned_value = waveYourFlag(arr)
print(f'Task 6: {returned_value}') # This should print [45,78,23,84,41]
unittest.output_test(returned_value, np.array([45,78,23,84,41]))

///  Test 06: Odd Even Wave  ///
Task 6: [2 3 8 1 5 1]
Not Accepted [Your output: [2 3 8 1 5 1]  |  Expected Output: [ 2  3 12  1  8  5]]
Task 6: [23 78 78 41 84]
Not Accepted [Your output: [23 78 78 41 84]  |  Expected Output: [45 78 23 84 41]]


In [ ]:
#Part 2

#01.

def mean(array):
    sum = 0
    for i in range(0,len(array)):
        sum += arr[i]
    mean = sum/len(array)
    return "The mean of the numbers is: " + str(mean)
arr = [10, 8, 13, 9, 14, 25, -5, 20, 7, 7, 4]
print(mean(arr))

#02.
def standard_deviation(array):
    sum = 0
    for i in range(0,len(array)):
        sum += arr[i]
    mean = sum/len(array)
    sum2 = 0
    N = len(arr)
    for j in range(0,len(array)):
       res = (array[j] - mean)**2
       sum2 += res
    SD = (sum2/(N-1))**0.5
    return "The standard deviation is: " + str(round((SD),2))
arr = [10, 8, 13, 9, 14, 25, -5, 20, 7, 7, 4]
print(standard_deviation(arr))

#03.
def Standard_Deviation(array):
  sum = 0
  for i in range(0,len(array)):
    sum += array[i]
  mean = sum/len(array)
  sum2 = 0
  N = len(array)
  for j in range(0,len(array)):
    res = (arr[j] - mean)**2
    sum2 += res
    SD = (sum2/(N-1))**0.5
  n_arr = [0]*len(array)
  a = 1.5
  up = mean + a*SD
  low = mean - a*SD
  count = 0
  for i in range(0,len(array)):
    if array[i] < low:
      n_arr[i] = array[i]
      count += 1
    elif array[i] > up:
      n_arr[i] = array[i]
      count += 1
  new_arr = [0]*count
  c1 = 0
  for j in range(len(n_arr)):
    if n_arr[j] != 0:
      new_arr[c1] = n_arr[j]
      c1 += 1
  return new_arr
arr = [10,8,13,9,14,25,-5,20,7,7,4]
print(Standard_Deviation(arr))

The mean of the numbers is: 10.181818181818182
The standard deviation is: 7.96
[25, -5]
